### ISSUE TITLE
Error: Unable to access application API - Deploy to Azure

### ISSUE THREAD

**Issue by isdataninja** [microsoft/Purview-Custom-Types-Tool-Solution-Accelerator#13]
![image](https://i.imgur.com/reifa7S.png)

I've ensured the step 7 is completed. I can confirm that these values are correct as my App starts up fine locally.
![image](https://i.imgur.com/3reHI5I.png)

Myself who is not familiar with Azure Functions, the next step to fix and resolve this issue is unclear. Kindly assist.
`Due to the two methods of [API support in Azure Static Web Apps with Azure Functions](https://docs.microsoft.com/en-us/azure/static-web-apps/apis), you need to manually create an Azure Function for the /api/AadToken endpoint. For more information, please follow the [Getting started with Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-get-started?pivots=programming-language-javascript) and learn how to [Bring your own functions to Azure Static Web Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own).`

**Comment by mattsavarino** [comment]
[API support in Azure Static Web Apps with Azure Functions](https://docs.microsoft.com/en-us/azure/static-web-apps/apis) has a table that contrasts the differences between using managed and existing functions. Note that `Azure App Service Authentication and Authorization` is not one of the managed functions and requires you to [bring your own functions to Azure Static Web Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own).

Specifically, the [api/AadToken](https://github.com/microsoft/Purview-Custom-Types-Tool-Solution-Accelerator/tree/main/api/AadToken) function needs to be recreated as a standalone Azure Function with the associated environment variables defined.
